const ACCESS_TOKEN_COOKIE = 'fefaAccess'
const REFRESH_TOKEN_COOKIE = 'fefaRefresh'
const POST_LOGIN_REDIRECT_QUERY = 'redirect_to'
const DEBOUNCER_TOLERANCE_MILLISECONDS = 600
const PAGINATION_PAGE_SIZE = 2

export {
  ACCESS_TOKEN_COOKIE,
  REFRESH_TOKEN_COOKIE,
  POST_LOGIN_REDIRECT_QUERY,
  DEBOUNCER_TOLERANCE_MILLISECONDS,
  PAGINATION_PAGE_SIZE
}
